name: Bug Report
description: Report a bug in the typesetting engine
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the issue
      placeholder: |
        1. Parse HTML '...'
        2. Apply CSS '...'
        3. Call layoutHTML(...)
        4. Observe incorrect output
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - macOS
        - iOS
        - Android
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Engine version or commit hash
    validations:
      required: false
