name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CSS Parsing
        - HTML Parsing
        - Layout Engine
        - Style Resolution
        - iOS Binding
        - Android Binding
        - Other
    validations:
      required: true
